# Generated by Django 2.1.7 on 2019-04-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
